// <auto-generated />
using System;
using DataLinkLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20181128102321_test3")]
    partial class test3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLinkLayer.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer");

                    b.Property<string>("CrypticClue");

                    b.Property<string>("Description");

                    b.Property<string>("Hint1");

                    b.Property<string>("Hint2");

                    b.Property<double?>("Lat");

                    b.Property<double?>("Long");

                    b.Property<string>("Naam");

                    b.Property<int?>("PilgrimageID");

                    b.HasKey("ID");

                    b.HasIndex("PilgrimageID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DataLinkLayer.Models.Pilgrimage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProfileID");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("Time");

                    b.HasKey("ID");

                    b.HasIndex("ProfileID");

                    b.ToTable("Pilgrimages");
                });

            modelBuilder.Entity("DataLinkLayer.Models.Profile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("Country");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("NickName");

                    b.Property<byte[]>("ProfilePicture");

                    b.Property<string>("base64");

                    b.Property<int>("fireBaseID");

                    b.HasKey("ID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("DataLinkLayer.Models.Location", b =>
                {
                    b.HasOne("DataLinkLayer.Models.Pilgrimage")
                        .WithMany("Locations")
                        .HasForeignKey("PilgrimageID");
                });

            modelBuilder.Entity("DataLinkLayer.Models.Pilgrimage", b =>
                {
                    b.HasOne("DataLinkLayer.Models.Profile")
                        .WithMany("CompletedPilgrimages")
                        .HasForeignKey("ProfileID");
                });
#pragma warning restore 612, 618
        }
    }
}
